## LU Decomposition

In [17]:
import numpy as np

In [18]:
MAX = 100; 

    
def luDecomposition(mat, n): 
  
    lower = [[0 for x in range(n)]  
                for y in range(n)]; 
    upper = [[0 for x in range(n)]  
                for y in range(n)]; 
                  
    # Decomposing matrix into Upper  
    # and Lower triangular matrix 
    for i in range(n): 
  
        # Upper Triangular 
        for k in range(i, n):  
  

           
            # Summation of L(i, j) * U(j, k) 
            sum = 0; 
            for j in range(i): 
                sum += (lower[i][j] * upper[j][k]); 
  
            # Evaluating U(i, k) 
            upper[i][k] = mat[i][k] - sum; 
  
        # Lower Triangular 
        for k in range(i, n): 
            if (i == k): 
                lower[i][i] = 1; # Diagonal as 1 
            else: 
  
                # Summation of L(k, j) * U(j, i) 
                sum = 0; 
                for j in range(i): 
                    sum += (lower[k][j] * upper[j][i]); 
  
                # Evaluating L(k, i) 
                lower[k][i] = int((mat[k][i] - sum) / upper[i][i]); 
  
    # setw is for displaying nicely 
    print("Lower Triangular\t\tUpper Triangular"); 
  
    # Displaying the result : 
    for i in range(n): 
          
        # Lower 
        for j in range(n): 
            print(lower[i][j], end = "\t");  
        print("", end = "\t"); 
  
        # Upper 
        for j in range(n): 
            print(upper[i][j], end = "\t"); 
        print(""); 
        
    print('\n L*U \n')
    print(np.dot(lower, upper))

mat = [[2, -1, -2], 
       [-4, 6, 3], 
       [-4, -2, 8]]; 
  
luDecomposition(mat, 3); 

Lower Triangular		Upper Triangular
1	0	0		2	-1	-2	
-2	1	0		0	4	-1	
-2	-1	1		0	0	3	

 L*U 

[[ 2 -1 -2]
 [-4  6  3]
 [-4 -2  8]]


In [1]:
MAX = 100  
    
    
def luDecomposition(mat, n): 
  
    lower = [[0 for x in range(n)]  
                for y in range(n)]; 
   
    upper = [[0 for x in range(n)]  
                for y in range(n)]; 

    
    for i in range(n): 
  
        # Upper Triangular 
        for k in range(i, n):  
  
            
            sum = 0; 
            for j in range(i): 
                sum += (lower[i][j] * upper[j][k]); 
  
          
            upper[i][k] = mat[i][k] - sum; 
            print("\n", upper[i][k])

    print("\n\n\nUpper Triangular"); 
  
    # Displaying the result : 
    for i in range(n): 
       
        for j in range(n): 
            print(upper[i][j], end = "\t"); 
        print(""); 
  
# Driver code 
mat = [[2, -1, -2], 
       [-4, 6, 3], 
       [-4, -2, 8]]; 
  
luDecomposition(mat, 3);


 2

 -1

 -2

 6

 3

 8



Upper Triangular
2	-1	-2	
0	6	3	
0	0	8	


In [19]:
MAX = 100    
def luDecomposition(mat, n): 
  
    lower = [[0 for x in range(n)]  
                for y in range(n)]; 
   
    upper = [[0 for x in range(n)]  
                for y in range(n)]; 

    for row in range(n): 
  
        # Upper matrix 
        for col in range(row, n):  
            sum = 0; 
            for j in range(row): 
                sum += (lower[row][j] * upper[j][col]); 
            
            upper[row][col] = mat[row][col] - sum;
 













                 
        
        # Displaying the result : 
    for i in range(n): 
     
        # Upper 
        for j in range(n): 
            print(upper[i][j], end = "\t"); 
        print(""); 

mat = [[2, -1, -2], 
       [-4, 6, 3], 
       [-4, -2, 8]]; 
  
luDecomposition(mat, 3);

2	-1	-2	
0	6	3	
0	0	8	


In [ ]:
# Summation of L(k, j) * U(j, i) 
                sum = 0; 
                for j in range(row): 
                    sum += (lower[col][j] * upper[j][row]); 
  
                # Evaluating L(k, i) 
                lower[col][row] = int((mat[col][row] - sum) /
                                       upper[row][row]);